name: Build Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn

    - name: Deploy
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Build Site GitHub Action"
        yarn deploy
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
        CI: true
